// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Address {
    #[prost(string, tag = "1")]
    pub street: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub city: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub country: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Contact {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub phone: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Person {
    /// Scalar fields - should always be T in proto3
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub age: i32,
    /// Message fields - should be Option<T> by default, T with force_required_messages
    #[prost(message, tag = "3")]
    pub home_address: Address,
    #[prost(message, tag = "4")]
    pub contact_info: Contact,
    /// Explicitly optional fields - should always be Option<T>
    #[prost(message, optional, tag = "5")]
    pub work_address: ::core::option::Option<Address>,
    #[prost(message, optional, tag = "6")]
    pub emergency_contact: ::core::option::Option<Contact>,
    /// Repeated fields - should always be Vec<T>
    #[prost(message, repeated, tag = "7")]
    pub previous_addresses: ::prost::alloc::vec::Vec<Address>,
    #[prost(message, repeated, tag = "8")]
    pub additional_contacts: ::prost::alloc::vec::Vec<Contact>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Company {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, tag = "2")]
    pub headquarters: Address,
    #[prost(message, repeated, tag = "3")]
    pub employees: ::prost::alloc::vec::Vec<Person>,
    #[prost(message, optional, tag = "4")]
    pub ceo: ::core::option::Option<Person>,
}
