// This file is @generated by prost-build.
/// Basic message with string and non-string fields.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Basic {
    #[prost(custom_string, tag = "1")]
    pub name: my_crate::CustomStr,
    #[prost(custom_string, tag = "2")]
    pub description: my_crate::CustomStr,
    #[prost(int32, tag = "3")]
    pub id: i32,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Message with repeated string field.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WithRepeated {
    #[prost(custom_string, repeated, tag = "1")]
    pub tags: ::prost::alloc::vec::Vec<my_crate::CustomStr>,
    #[prost(custom_string, tag = "2")]
    pub label: my_crate::CustomStr,
}
/// Message with map fields containing string keys and/or values.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithMap {
    #[prost(btree_map = "custom_string, custom_string", tag = "1")]
    pub labels: ::prost::alloc::collections::BTreeMap<my_crate::CustomStr, my_crate::CustomStr>,
    #[prost(btree_map = "custom_string, int32", tag = "2")]
    pub counts: ::prost::alloc::collections::BTreeMap<my_crate::CustomStr, i32>,
    #[prost(btree_map = "int32, custom_string", tag = "3")]
    pub names: ::prost::alloc::collections::BTreeMap<i32, my_crate::CustomStr>,
}
/// Message with a oneof containing a string variant.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WithOneof {
    #[prost(oneof = "with_oneof::Value", tags = "1, 2")]
    pub value: ::core::option::Option<with_oneof::Value>,
}
/// Nested message and enum types in `WithOneof`.
pub mod with_oneof {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Value {
        #[prost(custom_string, tag = "1")]
        Text(my_crate::CustomStr),
        #[prost(int32, tag = "2")]
        Number(i32),
    }
}
