// This file is @generated by prost-build.
/// Basic message with string and non-string fields.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Basic {
    #[prost(custom_string, tag = "1")]
    pub name: my_crate::CustomStr,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub id: i32,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Message with repeated string field.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WithRepeated {
    #[prost(string, repeated, tag = "1")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "2")]
    pub label: ::prost::alloc::string::String,
}
/// Message with map fields containing string keys and/or values.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithMap {
    #[prost(map = "string, string", tag = "1")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(map = "string, int32", tag = "2")]
    pub counts: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    #[prost(map = "int32, string", tag = "3")]
    pub names: ::std::collections::HashMap<i32, ::prost::alloc::string::String>,
}
/// Message with a oneof containing a string variant.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WithOneof {
    #[prost(oneof = "with_oneof::Value", tags = "1, 2")]
    pub value: ::core::option::Option<with_oneof::Value>,
}
/// Nested message and enum types in `WithOneof`.
pub mod with_oneof {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Value {
        #[prost(custom_string, tag = "1")]
        Text(my_crate::CustomStr),
        #[prost(int32, tag = "2")]
        Number(i32),
    }
}
