// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TestPacked {
    #[prost(int32, repeated, packed = "false", tag = "1")]
    pub no_options: ::prost::alloc::vec::Vec<i32>,
    #[deprecated]
    #[prost(int32, repeated, packed = "false", tag = "2")]
    pub other_options_only: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, packed = "false", tag = "3")]
    pub explicit_unpacked: ::prost::alloc::vec::Vec<i32>,
    #[deprecated]
    #[prost(int32, repeated, packed = "false", tag = "4")]
    pub explicit_unpacked_with_options: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, repeated, tag = "5")]
    pub explicit_packed: ::prost::alloc::vec::Vec<i32>,
    #[deprecated]
    #[prost(int32, repeated, tag = "6")]
    pub explicit_packed_with_options: ::prost::alloc::vec::Vec<i32>,
}
