// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Container {
    #[prost(oneof = "container::Data", tags = "1, 2")]
    pub data: Option<container::Data>,
}
/// Nested message and enum types in `Container`.
pub mod container {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "1")]
        Foo(Box<super::Foo>),
        #[prost(message, tag = "2")]
        Bar(super::Bar),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Foo {
    #[prost(string, tag = "1")]
    pub foo: String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Bar {
    #[prost(message, optional, boxed, tag = "1")]
    pub qux: Option<Box<Qux>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Qux {}
